@startuml
scale 2
title 11.新建admin接口方法（管理员后台页面）
start
->直接进入 /admin 网址接口;
 :查询所有资产;
note left
    管理员要这些资产干嘛呢？
    管理员要看看出库后外面有多少资产。
    所以我们需要准备这些模型数据
end note
:把查询的所有资产集合放入模型中;

:查询所有的入库单;
note left
    管理员是要出库的。
    在管理员的页面，没有入库单号，怎么完成出库操作呢？
end note
->所有入库单;
:把查询的所有入库单放入到模型中;

:查询所有的申请单;
note left
    管理员不就是做这个事情么。
    同意申请和拒绝申请等
end note
:把查询的所有申请单集合放入到模型中;

:没有想到还要放什么数据到模型里了
那就返回 admin 视图吧。
;
stop
@enduml