@startuml
scale 2
title 13.admin视图渲染入库单集合数据

start
note left
管理员主要的操作很多
资产入库
资产出库
查看资产
查看申请单等等;
end note
:资产入库;
:
{{
salt
{#
  字段| value属性|name属性
  资产名称 | "电脑       "|name
  资产数量| "32       "|amount
  资产类型|"办公用品     "|type
   [保存入库]|*
}
}}
;

:资产出库;

:
{{
salt
{-
    入库单号| ^电脑(4)^
    [开始出库]
}
}}
;

:资产列表;
:
{{
salt
{!
    二维码图片|二维码图片|二维码图片
    "电脑(7)"|"电脑(8)"|"手机(9)"
    入库单号: "4"|入库单号: "4"|入库单号: "3"
}
}}
;

:申请单列表;
:
{{
salt
{-
  申请人，资产名称，申请理由，资产类型    {[同意]|[拒绝]}
  user，电脑，扫码快速提交，领用    {[同意]|[拒绝]}
  admin，电脑，扫码快速提交，维修    {[同意]|[拒绝]}
}
}}
;
stop
@enduml