@startuml
autonumber
Web浏览器 -> 过滤器: 我要查看资产/assetById
过滤器 --> 首页控制器: 这个不归我管，放行，转给首页控制器
首页控制器->首页控制器: 执行/assetById对应的assetById()方法
首页控制器->首页控制器: 获得当前登录用户
首页控制器->首页控制器: 判断登录用户角色权限是admin还是user
alt 登录用户角色权限是user
首页控制器->首页控制器: 把维修和报废的接口地址放在数组的Model中（模型层）
else 登录用户角色权限是admin
首页控制器->首页控制器: 把收回和报废和分配的接口地址放在数组的Model中（模型层）
end
首页控制器->Web浏览器: 显示资产视图
@enduml