@startuml
scale 1.5
title 4.删除申请单类的amount数量属性
start
:找到申请单类，找到amount属性;
:双击选中amount属性;
:在amount上单击鼠标右键;
:在弹出的快捷菜单中选择 查找使用 ;
:
{{
salt
{-
剪切
复制
粘贴
<font color=red><b>查找使用(__U__)
重构
省略。。
}
}}
;
->注意看下面的边栏;
:从找到的选项中，依次双击修改或删除。;
:直到所有对申请单的amount的使用都删掉为止。;
stop
@enduml