@startuml
scale 1.5
title 5.处理申请单后资产使用者如何变化
[*] --> 管理员: 出库后的资产使用者为管理员（或null）
管理员-->张三: 管理员同意了张三的领用申请单
管理员 -->李四: 管理员同意了李四的借用申请

state 张三 {
[*] --> 已使用
    已使用-->维修1:维修申请
    note left:无论同意还是拒绝 使用者还是张三;
    已使用-->空闲1:归还申请
    note left:无论同意还是拒绝 使用者还是张三;
    维修1-->已使用:维修成功
    note left:使用者还是张三;
    维修1-->报废1:维修失败
    note left:使用者还是张三;
    报废1-->[*]
}
state 李四 {
    [*] --> 借用
    借用-->维修2:维修申请
    note left:无论同意还是拒绝 使用者还是李四;
    借用-->空闲2:归还申请
    note left:无论同意还是拒绝 使用者还是李四;
    维修2-->借用:维修成功
    note left:使用者还是李四;
    维修2-->报废2:维修失败
    note left:使用者还是李四;
    报废2-->[*]
}

@enduml