@startuml
scale 2
title 1.追踪资产维修记录需求分析业务建模
|客户|
:我要追踪资产维修记录;

    |开发人员|
    :啥？啥追踪？;
    :是要看维修记录吗？;

|客户|
:嗯？？也对，我先看看看有多少电脑（资产）维修过;
:同时我还能看到那台电脑修过几次（手指着地上的破电脑）;

        |开发人员|
        :哟，要求简(ting)单(duo);
        :您的意思是查看所有的维修单和单个资产的维修单吗？;

|客户|
:我不知道你说的什么;
:我就是想知道哪些电脑维修过，修了几次。;

    |开发人员|
    :老板，你来看看，哪些是你想看的，你就打个勾勾！
    {{
    salt
    {#
        资产名称|申请单类型|开始状态|结束状态|申请单状态（处理结果）|操作项|是你想要的么
        电脑    |维修    |已使用  |维修    | 待处理 | {[同意]|[拒绝]}|{[X]是的|[]不是的}
        电脑    |维修    |已使用  |维修    | 同意 | {[维修成功]|[维修失败]}|{[X]是的|[]不是的}
        电脑    |维修    |已使用  |维修    | 拒绝 | 处理结束|{[X]是的|[]不是的}
        电脑    |维修    |已使用  |维修    | 维修成功 | 处理结束|{[X]是的|[]不是的}
        电脑    |维修    |维修  |已使用    | 待处理 |  {[同意]|[拒绝]} |{[X]是的|[]不是的}
        电脑    |维修    |维修   |已使用   | 同意 | 处理结束|{[X]是的|[]不是的}
        电脑    |维修    |维修   |报废   | 同意 | 处理结束|{[X]是的|[]不是的}
        电脑    |领用    |空闲   |已使用   | 同意 | 处理结束|{[]是的|[X]不是的}
        电脑    |领用    |空闲   |已使用   | 拒绝 | 处理结束|{[]是的|[X]不是的}
        电脑    |借用    |空闲   |借用   | 同意 | 处理结束|{[]是的|[X]不是的}
        电脑    |借用    |空闲   |借用   | 拒绝 | 处理结束|{[]是的|[X]不是的}
        电脑    |借用    |借用   |空闲   | 同意 | 处理结束|{[]是的|[X]不是的}
        电脑    |借用    |借用   |空闲   | 拒绝 | 处理结束|{[]是的|[X]不是的}
    }
    }}
    ;
    :明白了，我知道你想看什么了;


@enduml