@startuml

|登录控制器|
(A)
:接收密码参数1;
:接收用户名参数2;
|#eee|用户持久化类|
:通过用户名查询用户对象;
|登录控制器|
if (用户对象==null) then (yes)
:用户名不存在 ;
(no) elseif (用户对象.密码!=密码参数1) then (yes)
:密码错误;
else (no)
:登录成功;
:保存用户对象到session中;
endif
stop
@enduml