@startuml
scale 2
|登录控制器(1分)|
start
:接收用户对象参数(1分);
|#eee|用户持久化类(1分)|
:通过用户的用户名查询用户对象保存在变量u中(1分);
|登录控制器(1分)|
if (用户对象不存在吗(1分)) then (yes(1分))
:在模型层中加入错误提示"用户名不存在"(1分);
:返回到登录视图(1分);
stop
endif
->No(1分);
if (密码不正确吗(1分)) then (yes(1分))
:在模型层中加入错误提示“密码错误”(1分) ;
:返回到登录视图(1分);
stop
endif
->No(1分);
:将成功登录的用户对象保存在session会话对象中(1分);
:返回登录用户对象的权限视图(1分);

stop
@enduml