@startuml
scale 2
[*] --> 加工IP地址: IP地址
加工IP地址:1
[*] --> 加工URL地址: 完整URL
加工URL地址:2
[*] --> 加工浏览器信息: 浏览器信息
加工浏览器信息:3
[*] --> 加工登录用户信息: 登录用户
加工登录用户信息:4
加工IP地址 --> [*] : IP归属地
加工URL地址 --> [*] : 接口地址
加工浏览器信息 --> [*] : 操作系统
加工登录用户信息 --> [*] : 用户名
加工登录用户信息 --> [*] : 未登录

@enduml