@startmindmap
title 5.生命周期-可行性研究
* 可行性研究
** 经济可行性
*** 无成本，经济上可行

** 技术可行性
*** 技术储备
**** 过滤器知识-√
**** 控制层知识-√
**** 持久化知识-√
**** 视图模版引擎-√
**** MVC三层结构的理解-√
**** Java编码能力-√
*** 技术结论-可行

** 操作可行性
*** 法律可行性
**** 无违法行为，也没有侵权第三方行为，完全自主研发。
*** 法律可行性结论-可行
@endmindmap