@startmindmap
* 测试日志子系统
** 未登录
*** 访问首页（无权限限制页面）
**** 登录用户名是 未登录
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：空
***** 测试结果：通过/失败

*** 访问/admin（管理员后台）
**** 登录用户名是 未登录
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：返回登录/login/
***** 测试结果：通过/失败

*** 访问/user（使用者后台）
**** 登录用户名是 未登录
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：返回登录/login/
***** 测试结果：通过/失败

*** 访问/xyz（不存在页面）
**** 登录用户名是 未登录
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：返回登录/login/
***** 测试结果：通过/失败

** 管理员登录
*** 访问首页（无权限限制页面）
**** 登录用户名是 admin
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：空
***** 测试结果：通过/失败

*** 访问/admin（管理员后台）
**** 登录用户名是 admin
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：空
***** 测试结果：通过/失败

*** 访问/user（使用者后台）
**** 登录用户名是 admin
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：没有使用者权限 返回登录
***** 测试结果：通过/失败

*** 访问/xyz（不存在页面）
**** 登录用户名是 admin
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：空
***** 测试结果：通过/失败

** 使用者登录
*** 访问首页（无权限限制页面）
**** 登录用户名是 user
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：空
***** 测试结果：通过/失败

*** 访问/admin（管理员后台）
**** 登录用户名是 user
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：没有管理员权限 返回登录
***** 测试结果：通过/失败

*** 访问/user（使用者后台）
**** 登录用户名是 user
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：空
***** 测试结果：通过/失败

*** 访问/xyz（不存在页面）
**** 登录用户名是 user
***** 测试结果：通过/失败
**** 有保存结果
***** 测试结果：通过/失败
**** 返回结果：空
***** 测试结果：通过/失败
@enduml