@startmindmap
+ 申请单(含维修操作)
++ 空闲
+++ 开始和停止状态:**使用** => //空闲//
++++ 处理结果:待处理
+++++_ 资产状态：使用
+++++ **管理员操作项：同意、拒绝**

++++ 处理结果:同意
+++++_ 资产状态：空闲
+++++_ 管理员操作项：处理结束

++++ 处理结果:拒绝
+++++_ 资产状态：使用
+++++_ 管理员操作项：处理结束

+++ 开始和停止状态:**借用** => //空闲//
++++ 处理结果:待处理
+++++_ 资产状态：借用
+++++ 管理员操作项：同意、拒绝

++++ 处理结果:同意
+++++_ 资产状态：空闲
+++++_ 管理员操作项：处理结束

++++ 处理结果:拒绝
+++++_ 资产状态：借用
+++++_ 管理员操作项：处理结束

+++ 开始和停止状态:**维修** => //空闲//
++++ 处理结果:待处理
+++++_ 资产状态：维修
+++++ **管理员操作项：同意、拒绝**

++++ 处理结果:同意
+++++_ 资产状态：空闲
+++++_ 管理员操作项：处理结束

++++ 处理结果:拒绝
+++++ 资产状态：维修
+++++ 管理员操作项：维修成功、维修失败



++ 使用
+++ 开始和停止状态:**空闲** => //使用//
++++ 处理结果:待处理
+++++_ 资产状态：空闲
+++++ **管理员操作项：同意、拒绝**

++++ 处理结果:同意
+++++_ 资产状态：使用
+++++_ 管理员操作项：处理结束

++++ 处理结果:拒绝
+++++_ 资产状态：空闲
+++++_ 管理员操作项：处理结束

+++ 开始和停止状态:**维修** => //使用//
++++ 处理结果:待处理
+++++_ 资产状态：维修
+++++ **管理员操作项：同意、拒绝**

++++ 处理结果:同意
+++++_ 资产状态：使用
+++++_ 管理员操作项：处理结束

++++ 处理结果:拒绝
+++++ 资产状态：维修
+++++ 管理员操作项：维修成功、维修失败


++ 借用
+++ 开始和停止状态:**空闲** => //借用//
++++ 处理结果:待处理
+++++_ 资产状态：空闲
+++++ **管理员操作项：同意、拒绝**

++++ 处理结果:同意
+++++_ 资产状态：借用
+++++_ 管理员操作项：处理结束

++++ 处理结果:拒绝
+++++_ 资产状态：空闲
+++++_ 管理员操作项：处理结束

+++ 开始和停止状态:**维修** => //借用//
++++ 处理结果:待处理
+++++_ 资产状态：维修
+++++ **管理员操作项：同意、拒绝**

++++ 处理结果:同意
+++++_ 资产状态：借用
+++++_ 管理员操作项：处理结束

++++ 处理结果:拒绝
+++++ 资产状态：维修
+++++ 管理员操作项：维修成功、维修失败

-- 维修
--- 开始和停止状态:**空闲** => //维修//
---- 处理结果:待处理
-----_ 资产状态：空闲
----- **管理员操作项：同意、拒绝**

---- 处理结果:同意
----- 资产状态：维修
----- 管理员操作项：维修成功、维修失败

---- 处理结果:拒绝
-----_ 资产状态：空闲
-----_ 管理员操作项：处理结束

--- 开始和停止状态:**使用** => //维修//
---- 处理结果:待处理
-----_ 资产状态：使用
----- **管理员操作项：同意、拒绝**

---- 处理结果:同意
----- 资产状态：维修
----- 管理员操作项：维修成功、维修失败

---- 处理结果:拒绝
-----_ 资产状态：使用
-----_ 管理员操作项：处理结束

--- 开始和停止状态:**借用** => //维修//
---- 处理结果:待处理
-----_ 资产状态：借用
----- **管理员操作项：同意、拒绝**

---- 处理结果:同意
----- 资产状态：维修
----- 管理员操作项：维修成功、维修失败

---- 处理结果:拒绝
-----_ 资产状态：借用
-----_ 管理员操作项：处理结束


-- 报废
--- 开始和停止状态:**空闲** => //报废//
---- 处理结果:待处理
-----_ 资产状态：空闲
----- **管理员操作项：同意、拒绝**

---- 处理结果:同意
-----_ 资产状态：报废
-----_ 管理员操作项：处理结束

---- 处理结果:拒绝
-----_ 资产状态：空闲
-----_ 管理员操作项：处理结束

--- 开始和停止状态:**维修** => //报废//
---- 处理结果:待处理
-----_ 资产状态：维修
----- **管理员操作项：同意、拒绝**

---- 处理结果:同意
-----_ 资产状态：报废
-----_ 管理员操作项：处理结束

---- 处理结果:拒绝
----- 资产状态：维修
----- 管理员操作项：维修成功、维修失败

--- 开始和停止状态:**使用** => //报废//
---- 处理结果:待处理
-----_ 资产状态：使用
----- **管理员操作项：同意、拒绝**

---- 处理结果:同意
-----_ 资产状态：报废
-----_ 管理员操作项：处理结束

---- 处理结果:拒绝
-----_ 资产状态：使用
-----_ 管理员操作项：处理结束

--- 开始和停止状态:**借用** => //报废//
---- 处理结果:待处理
-----_ 资产状态：借用
----- **管理员操作项：同意、拒绝**

---- 处理结果:同意
-----_ 资产状态：报废
-----_ 管理员操作项：处理结束

---- 处理结果:拒绝
-----_ 资产状态：借用
-----_ 管理员操作项：处理结束

@endmindmap