@startuml
scale 2
title 分析从数据到视图的过程
start
:数据表里面
{{
salt
{#
  申请单ID|申请单名称|申请单状态|开始状态|结束状态
  1|电脑|同意|空闲|使用
  2|电脑|待处理|维修|使用
  3|手机|待处理|空闲|使用
}
}}
;
->持久化层获得之后;
:
{{
salt
{^ 申请单对象
  申请单ID|"1    "
  申请单名称|"电脑   "
  申请单状态|"同意  "
  开始状态|"空闲   "
  结束状态|"使用   "
}
}}
;
->经过服务层处理后;
fork
:其中一个对象
{{
salt
{^ 申请单对象
  申请单ID|"1    "
  申请单名称|"电脑   "
  申请单状态|"同意  "
  开始状态|"空闲   "
  结束状态|"使用   "
  管理员操作项|"处理结束"
}
}}
;
fork again
:其中另一个对象
{{
salt
{^ 申请单对象
  申请单ID|"2    "
  申请单名称|"电脑   "
  申请单状态|"待处理  "
  开始状态|"空闲   "
  结束状态|"使用   "
  管理员操作项|"<button>同意</button><button>拒绝</button>"
}
}}
;
end fork
->经过视图层渲染后;
:
{{
salt
{#
  申请单ID|申请单名称|申请单状态|开始状态|结束状态|管理员操作项
  1|电脑|同意|空闲|使用|处理结束
  2|电脑|待处理|维修|使用|{[同意]|[拒绝]}
  3|手机|待处理|空闲|使用|{[同意]|[拒绝]}
}
}}
;

stop
@enduml