@startuml
scale 2
title 8-1.点击维修成功的流程
|管理员|
start
:我是在哪张申请单上点击的“维修成功”和“维修失败”;
->获得申请号;
:告诉系统，这个申请单号我维修成功了;
->/application/repairOk?applicationId=7;
    |申请单控制器-维修成功|
    :拿到传递过来的申请单ID=7获得申请单;
    :获得申请单的结束状态（维修）;
    :获得申请单的开始状态（假设是使用）;
    partition 新加入的流程 {
        :ID=7的申请单状态为： 维修成功;
        :ID=7的申请单处理人为： 当前登录用户（维修员）;
        :ID=7的申请单时间为： new Date();
        :ID=7的申请单处理意见为： "这是维修成功的流程，系统自动填写";
        :ID=7的申请单操作项为： "维修结束";
    }
    partition 创建申请单 {
        :新建申请单对象;
        #fdd:新对象的开始状态 = 原来申请单的结束状态;
        #fdd:新对象的结束状态 = 原来申请单的开始状态;
        #fdd:新对象的申请时间 = new Date();
        #fdd:新对象的状态 = 待处理;
        #fdd:<b>新对象的申请人 = 原来申请单的申请人</b>;

        #dfd:新对象的资产ID = 原来申请单的资产ID;
        #dfd:新对象的资产名称 = 原来申请单的资产名称;
        #dfd:新对象的资产用途 = 原来申请单的资产用途;
        #dfd:新对象的类型 = 原来申请单的类型;
        #f0f:<s>新对象的资产数量 =  原来申请单的资产数量</s>;

        #ddf:新对象的处理时间 = null;
        #ddf:新对象的处理人 = null;
        #ddf:新对象的处理意见 = null;
    }
    :保存申请单;

stop
@enduml