@startuml
scale 1
title 维修成功和失败
|管理员|
start
:又有人要来维修;
:查看维修单
{{
salt
{-
 申请人  |类型  |状态    |开始状态  |结束状态|操作
 "张三"|"维修"|"待处理  "|已使用|维修|{[同意] | [拒绝]}
 "李四"|"维修"|"待处理  "|已使用|维修|{[同意] | [拒绝]}
 "王五"|"维修"|"待处理  "|已使用|维修|{[同意] | [拒绝]}
 "赵六"|"维修"|"待处理  "|已使用|维修|{[同意] | [拒绝]}
}
}}
;

:先修张三和李四的，王五的是接触不良，已经电话解决了，直接X掉;
:点击“同意”按钮
{{
salt
{-
 申请人  |类型  |状态    |开始状态  |结束状态|操作
 "张三"|"维修"|"同意  "|已使用|维修|{[维修成功] | [维修失败]}
 "李四"|"维修"|"同意  "|已使用|维修|{[维修成功] | [维修失败]}
 "王五"|"维修"|"拒绝  "|已使用|维修|**处理结束**
 "赵六"|"维修"|"待处理  "|已使用|维修|{[同意] | [拒绝]}
}
}}
;

:张三的修好了;
:点击“维修成功”按钮
{{
salt
{-
 申请人  |类型  |状态    |开始状态  |结束状态|操作
 "张三"|"维修"|"维修成功"|已使用|维修|//维修结束//
 "<&share>张三"|"维修"|"待处理"|维修|已使用|{[同意] | [拒绝]}
 "李四"|"维修"|"同意    "|已使用|维修|{[维修成功] | [维修失败]}
 "王五"|"维修"|"拒绝    "|已使用|维修|**处理结束**
 "赵六"|"维修"|"待处理   "|已使用|维修|{[同意] | [拒绝]}
}
}}
;

:李四的修不好;
:点击“维修失败”按钮
{{
salt
{-
 申请人  |类型  |状态    |开始状态  |结束状态|操作
 "张三"|"维修"|"维修成功"|已使用|维修|//维修结束//
 "<&share>张三"|"维修"|"待处理   "|维修|已使用|{[同意] | [拒绝]}
 "李四"|"维修"|"维修失败  "|已使用|维修|//维修结束//
 "<&share>李四"|"维修"|"待处理   "|维修|报废|{[同意] | [拒绝]}
 "王五"|"维修"|"拒绝    "|已使用|维修|**处理结束**
 "赵六"|"维修"|"待处理   "|已使用|维修|{[同意] | [拒绝]}
}
}}
;

:同意张三的维修意见;
:点击“同意”按钮
{{
salt
{-
 申请人  |类型  |状态    |开始状态  |结束状态|操作
 "张三"|"维修"|"维修成功"|已使用|维修|//维修结束//
 "<&share>张三"|"维修"|"同意   "|维修|已使用| **//处理结束//**
 "李四"|"维修"|"维修失败  "|已使用|维修|//维修结束//
 "<&share>李四"|"维修"|"待处理   "|维修|报废|{[同意] | [拒绝]}
 "王五"|"维修"|"拒绝    "|已使用|维修|**处理结束**
 "赵六"|"维修"|"待处理   "|已使用|维修|{[同意] | [拒绝]}
}
}}
;


:拒绝李四的维修意见;
:点击“拒绝”按钮
{{
salt
{-
 申请人  |类型  |状态    |开始状态  |结束状态|操作
 "张三"|"维修"|"维修成功"|已使用|维修|//维修结束//
 "<&share>张三"|"维修"|"同意   "|维修|已使用| **//处理结束//**
 "李四"|"维修"|"维修失败  "|已使用|维修|//维修结束//
 "<&share>李四"|"维修"|"拒绝   "|维修|报废|{[维修成功] | [维修失败]}
 "王五"|"维修"|"拒绝    "|已使用|维修|**处理结束**
 "赵六"|"维修"|"待处理   "|已使用|维修|{[同意] | [拒绝]}
}
}}
;


:李四的还是修不好;
:点击“维修失败”按钮
{{
salt
{-
 申请人  |类型  |状态    |开始状态  |结束状态|操作
 "张三"|"维修"|"维修成功"|已使用|维修|//维修结束//
 "<&share>张三"|"维修"|"同意   "|维修|已使用| **//处理结束//**
 "李四"|"维修"|"维修失败  "|已使用|维修|//维修结束//
 "<&share>李四"|"维修"|"维修失败   "|维修|报废|//维修结束//
 "<&share>李四"|"维修"|"待处理   "|维修|报废|{[同意] | [拒绝]}
 "王五"|"维修"|"拒绝    "|已使用|维修|**处理结束**
 "赵六"|"维修"|"待处理   "|已使用|维修|{[同意] | [拒绝]}
}
}}
;


:妥协了李四的维修意见;
:点击“同意”按钮
{{
salt
{-
 申请人  |类型  |状态    |开始状态  |结束状态|操作
 "张三"|"维修"|"维修成功"|已使用|维修|//维修结束//
 "<&share>张三"|"维修"|"同意   "|维修|已使用| **//处理结束//**
 "李四"|"维修"|"维修失败  "|已使用|维修|//维修结束//
 "<&share>李四"|"维修"|"维修失败   "|维修|报废|//维修结束//
 "<&share>李四"|"维修"|"同意   "|维修|报废| **//处理结束//**
 "王五"|"维修"|"拒绝    "|已使用|维修|**处理结束**
 "赵六"|"维修"|"待处理   "|已使用|维修|{[同意] | [拒绝]}
}
}}
;
stop
@enduml