@startmindmap
* 扫码
** 管理员
*** 收回资产<&check>
**** 资产状态为空闲
*** 设置维修<&check>
**** 资产状态为维修
*** 设置报废<&check>
**** 资产状态为报废
*** 提交领用申请<&check>
**** 新增申请单
**** 申请单类型为报废
*** 提交维修申请<&check>
**** 新增申请单
**** 申请单类型为报废
*** 提交报废申请<&check>
**** 新增申请单
**** 申请单类型为报废

** 普通用户
*** 收回资产<&x>
**** 返回登录页
*** 设置维修<&x>
**** 返回登录页
*** 设置报废<&x>
**** 返回登录页
*** 提交领用申请<&check>
**** 新增申请单
**** 申请单类型为领用
*** 提交维修申请<&check>
**** 新增申请单
**** 申请单类型为维修
*** 提交报废申请<&check>
**** 新增申请单
**** 申请单类型为报废

** 未登录
*** 收回资产<&x>
**** 返回登录页
*** 设置维修<&x>
**** 返回登录页
*** 设置报废<&x>
**** 返回登录页
*** 提交领用申请<&x>
**** 返回登录页
*** 提交维修申请<&x>
**** 返回登录页
*** 提交报废申请<&x>
**** 返回登录页
@endmindmap