@startuml
scale 2
actor 用户
用户 -> 浏览器: 访问资产页
box 系统边界
浏览器 -> 过滤器: 检查网址映射表
过滤器 -> 控制器: 用户要看资产页
end box
box 系统组成
控制器 -> 会话层Session:  谁要看资产页
控制器 -> 持久化层: 查询资产
控制器 -> 模型层: 把资产放进去
控制器 -> 视图层: 渲染数据显示结果
视图层 --> 浏览器: 渲染完毕，呈现网页
浏览器 -->用户: 满足用户需求
end box
@enduml