@startuml
scale 2
title 维修成功和失败
|管理员|
start
:申请单已经同意维修了;
->资产状态是维修状态;
    |维修员|
    :修好了;
    :我怎么样才能让资产状态变回原来的状态;

|管理员|
:检查维修的申请单;
->获得开始状态和结束状态;
:点击“维修成功”按钮
{{
salt
{-
 姓名  |类型  |状态    |开始状态  |结束状态|操作
 "张三"|"维修"|"同意  "|已使用|维修|{[维修成功] | [维修失败]}
 "李四"|"领用"|"同意  "|空闲|已使用|**//处理结束//**
 "王五"|"报废"|"拒绝  "|已使用|报废|**//处理结束//**
 "赵六"|"维修"|"待处理"|借用|维修|{[同意] | [拒绝]}
}
}}
;
|系统自动操作|
:自动创建新的申请单
{{
salt
{^ 自动提交申请单
    申请单的申请人： | "维修员/管理员"
    申请单类型： | "维修成功"
    申请单开始状态： | 维修
    申请单结束状态： | 来自原来申请单的开始状态
}
}}
;
|管理员|
:同意维修成功
{{
salt
{-
 姓名  |类型  |状态    |开始状态  |结束状态|操作
 "张三"|"维修"|"同意  "|已使用|维修|{[维修成功] | [维修失败]}
 "李四"|"领用"|"同意  "|空闲|已使用|**//处理结束//**
 "王五"|"报废"|"拒绝  "|已使用|报废|**//处理结束//**
 "赵六"|"维修"|"待处理"|借用|维修|{[同意] | [拒绝]}
 "赵六"|"维修成功"|"待处理"|维修|已使用|{[同意] | [拒绝]}
 "赵六"|"维修失败"|"待处理"|维修|报废|{[同意] | [拒绝]}
}
}}
;

stop
@enduml