@startuml
'scale 350 width
scale 1
[*] --> 无状态:资产入库
note right
资产入库时只有一张单据，
并没有任何资产实体出现。
end note
无状态 --> 空闲:资产出库
空闲 --> 预定: 收到<b>领用申请
预定 --> 已使用:同意<b>领用申请
预定 --> 空闲:拒绝<b>领用申请

空闲 --> 借用: 同意<b>借用</b>申请
空闲 --> 报废: 管理员直接设置为“报废”
借用 --> 空闲: 同意<b>归还申请

空闲 --> 维修: 管理员直接设置资产状态为“维修”
维修 -[#green,dashed]-> 空闲: 维修成功

已使用 -->空闲: 同意<b>归还申请
已使用 -->维修: 同意<b>维修申请
维修 -[#green,dashed]-> 已使用: 维修成功
维修 --> 报废: 修不好

已使用 -->报废: 同意报废申请

@enduml