@startuml
'scale 350 width
scale 2
[*] --> 无状态:资产入库
note right
资产入库时只有一张单据，
并没有任何资产实体出现。
end note
无状态 --> 空闲:资产出库
空闲 --> 已使用:同意领用申请
空闲 --> 借用: 同意借用申请
'空闲 --> 维修: 管理员直接设置资产状态为“维修”
'空闲 --> 报废: 管理员直接设置资产状态为“维修”

已使用 -[#green,dashed]->空闲: 同意归还申请
已使用 -->维修: 同意维修申请
已使用 -->报废: <&x>同意报废申请

借用 -[#green,dashed]-> 空闲: 同意归还申请
借用 --> 维修: 同意维修申请

维修 -[#green,dashed]-> 空闲: 维修成功
维修 -[#green,dashed]-> 已使用: 维修成功
维修 -[#red,bold]-> 报废: 修不好


@enduml