@startuml
scale 2
title 我的电脑经过维修后
|我的电脑|
start
:我电脑坏了;
:我申请维修一下;
->提交了维修申请单;

    |资产管理系统|
    :收到维修单子;
    ->同意维修申请;
    :管理员安排维修人员开始修理;
    :经过10分钟后修好了;

        |仓库|
        ->设置为空闲状态;
        :放到仓库中堆起来;
detach
|我的电脑|
:我电脑呢？
去哪儿了？;
->查看空闲资产;
    |资产管理系统|
    :把空闲资产给他看看;
    ->返回所有空闲资产;
|我的电脑|
:看到了自己的电脑!;
:正要重新提交申请，
发现这台电脑刚刚被分配给别人;
stop
@enduml