@startuml
scale 2
title 资产新增目标状态

|使用者-张三|
start
:我写领用申请，要资产：ID3;
:提交领用申请单;

    |系统|
    :检测到申请单上的资产是：ID3;
    :把资产ID3的目标状态改为“已使用”;
    note right
     这里暂不使用“预定”状态
     一定管理员同意就把资产ID3改为“已使用”
    end note
|使用者-李四|
:我偏要写报废申请，把ID3资产报废它;

    |系统|
    :检测到申请单上的资产是：ID3;
    :把资产ID3的目标状态改为“报废”;
    note right
        由于资产状态值有个属性，无法记录多个使用者的请求状态。
        所以，不适合将目标状态放入到资产中。
    end note
stop
@enduml