@startuml
scale 2
title 资产新增目标状态

|使用者-张三|
start
:提交维修申请单(ID3资产);

    |系统|
    :检测到申请单上的资产是：ID3;
    :把资产ID3的目标状态改为“维修”;
    :等管理员处理;
    detach
|使用者-张三|
:提交报废申请单(ID3资产);

    |系统|
    :检测到申请单上的资产是：ID3;
    :把资产ID3的目标状态改为“报废”;
note
那么该资产ID3的目标状态是什么？
end note
stop
@enduml