@startuml
scale 2
title 4.管理员处理申请单双状态

|系统|
start
:查看申请单;
:等待管理员处理;
fork
    :如果是维修申请;
    if (同意) then (Yes)
        :获得申请单开始状态（已使用）;
        :获得申请单停止状态（维修）;
        :获得申请单的资产ID(查询略);
        :设置资产状态申请单停止状态（维修）;
        #0f0:资产状态变更成功（维修）;
    else (No)
        :不作处理 资产状态不变 （仍然是已使用）;
    endif

fork again
    :如果是归还申请;
    if (同意) then (Yes)
        :获得申请单开始状态（借用）;
        :获得申请单停止状态（空闲）;
        :获得申请单的资产ID(查询略);
        :设置资产状态申请单停止状态（空闲）;
        #0f0:资产状态变更成功（空闲）;
    else (No)
        :不作处理 资产状态不变 （仍然是借用）;
    endif

fork again
    :如何处理维修结果;
    if (维修成功) then (Yes)
        :获得维修申请单-原申请单;
        :直接创建新的申请单-新申请单;
        :设置新申请单开始状态为（维修）;
        :设置新申请单的结束状态为（原申请单的开始状态）;
    else (No)
        :维修失败了，直接修改资产状态为“报废”;
    endif

fork again
    :如果是领用申请;
    if (同意) then (Yes)
        :获得申请单开始状态（空闲）;
        :获得申请单停止状态（领用==已使用）;
        :获得申请单的资产ID(查询略);
        #0f0:设置资产状态申请单停止状态（已使用）,
        根据维修申请单找到原来的状态;
    else (拒绝)
        :不作处理 资产状态不变 （仍然是借用）;
    endif

stop

@enduml