@startuml
scale 2
title 处理常规申请-双状态

start
fork
    partition 我是使用者 {
    :<&person>我是使用者;
    :提交领用申请;
    :记录开始状态（空闲）;
    :记录停止状态（已使用）;
    }
fork again
    :<&person>我是借用者;
    :提交借用申请;
    :记录开始状态（空闲）;
    :记录停止状态（借用）;
fork again
    partition 我是使用者 {
    :<&people>我是使用者;
    :提交归还申请;
    :记录开始状态（已使用）;
    :记录停止状态（空闲）;
    }
fork again
    :<&person>我是借用者;
    :提交归还申请;
    :记录开始状态（借用）;
    :记录停止状态（空闲）;
fork again
    partition 我是使用者 {
    :<&person>我是使用者;
    :提交维修申请;
    :记录开始状态（已使用）;
    :记录停止状态（维修）;
    }
fork again
    :<&person>我是借用者;
    :提交维修申请;
    :记录开始状态（借用）;
    :记录停止状态（维修）;
fork again
    partition 我是使用者 {
    :<&person>我是使用者;
    :提交报废申请;
    :记录开始状态（已使用）;
    :记录停止状态（报废）;
    }
end fork

->提交归还申请;
:收到归还申请;
:等待管理员处理;
if (同意处理) then (同意)
    :把资产状态设置为申请单的停止状态;
note
    资产状态 = 申请单停止状态
end note

else (拒绝)
    :资产状态 = 申请单开始状态;
endif



stop
@enduml