@startuml
scale 2
title 7.从领用到处理结束完整流程
|使用者|
start
:资产入库;
:资产出库;
:查看空闲资产;
:选择ID3提交领用申请;

    |系统自动处理的内容|
    :创建新的申请单;
    :申请单.类型 = "领用";
    :申请单.开始状态 = ID3资产的当前状态(空闲);
    :申请单.结束状态 = "已使用";
    :其它属性省略...;

        |管理员|
        :处理申请;
        if (同意) then (同意)
        :从申请单中获得资产;
        :资产状态 = 申请单.结束状态;
        else (拒绝)
        :从申请单中获得资产;
        :资产状态 = 申请单.开始状态;
        endif

stop
@enduml