@startuml
scale 2
title 4.维修中的bug
|使用者|
start
:提交维修申请;
:申请单ID=1;
:
{{
salt
{#
 申请单ID|姓名  |类型  |开始状态  |结束状态 |状态    |操作
 1      |"张三"|"维修"|已使用    |维修     |"待处理"|{[同意]|[拒绝]}
}
}}
;
    |管理员|
    :申请单ID=1 同意维修申请;
    :
    {{
    salt
    {#
     申请单ID|姓名  |类型  |开始状态  |结束状态 |状态    |操作
     1      |"张三"|"维修"|已使用|维修|"同意"|{[维修成功]|[维修失败]}
    }
    }}
    ;

    :申请单ID=1 维修失败;
    : 创建新的申请单
    {{
    salt
    {#
     申请单ID|姓名  |类型  |开始状态     |结束状态 |状态    |操作
     1      |"张三"|"维修"|已使用       |维修    |"维修失败"|处理结束
     2      |"张三"|"维修"|已使用       |报废     |"待处理"|{[同意]|[拒绝]}
    }
    }}
    ;

    :申请单ID=2 拒绝申请;
    :
    {{
    salt
    {#
     申请单ID|姓名  |类型  |开始状态     |结束状态 |状态    |操作
     1      |"张三"|"维修"|已使用|维修  |"维修成功"|处理结束
     2      |"张三"|"维修"|已使用  |报废|"拒绝"|处理结束
    }
    }}
    ;

stop
@enduml