@startuml
scale 2
|现状|
start
:领用申请单（ID=1）;
->管理员同意领用申请;
:提交维修申请单（ID=2）;
->同意维修;
:ID=2的申请单维修成功，产生ID=3申请单;
->管理员说没修好，拒绝ID=3;
:继续维修，把ID=3的申请单又修好了，产生了ID=4的申请单;
->管理员同意了ID=4的申请单;
note
请问，申请单的顺序是？？？
谁先谁后？
end note

stop
@enduml