@startuml
(*)  --> "接收到申请单号参数1"
--> "接收到申请单处理意见参数2"
-->"通过【申请单持久化对象】调用findById获得申请单"
If "申请单==null" then
--> [Yes] (*)
else
Endif
--> [No] "获得申请单中的资产ID"
--> "通过【资产持久化对象】调用findById获得资产"
If "资产==null" then
--> [Yes] (*)
else
Endif
--> [No] "获得资产的状态"
If "资产状态 != 已使用" then
--> [Yes] (*)
else
Endif
--> "修改资产状态为 报废"
--> "通过【资产持久化对象】调用save更新资产到数据库"
--> "设置申请单状态为 同意"
--> "设置申请单处理人为【当前登录对象】"
--> "设置申请单时间为 【当前时间】"
--> "设置申请单处理意见为 【参数2】"
--> "调用【申请单持久化对象】的save更新申请单"
-->(*)
@enduml