@startuml
(*)  --> "接收申请单参数"
--> "调用申请单持久化的findById获得申请单"
If "申请单==null" then
--> [Yes] (*)
else
Endif
--> [no]"从申请单中获得资产ID"
--> "调用资产持久化的findById获得资产"
if "资产==null" then
--> [yes] (*)
else
Endif
--> [no]"获得资产状态"
--> "获得申请单类型"
if "类型!=报废" then
--> [yes] (*)
else
Endif
if "状态!=已使用" then
--> [yes] (*)
else
Endif
-->[no] 设置资产状态为报废
--> 更新资产到数据库

--> 设置申请状态为同意
--> "设置申请单处理人为【当前登录用户】"
--> 设置处理结果为参数
-->"设置处理日期为【当前日期】"
-->更新申请单到数据库
-->(*)
@enduml