@startuml
(*)  --> "获得参数1申请单号和参数2处理意见"
--> "申请单持久化调用findById获得申请单"
If "申请单 == null" then
-->[Yes] (*)
Else
Endif
--> [No] "获得申请单中的资产ID"
--> "通过资产ID获得资产"
--> "获得资产状态"
If "资产状态==预定" then
--> [Yes] "设置资产状态为空闲"
--> "更新资产到数据库"
-->"设置申请单状态为 拒绝"
Else
Endif
-->[No]"设置申请单状态为 拒绝"
--> "设置申请单处理人为【当前登录用户】"
--> "设置处理意见为参数2"
--> "设置处理时间为【当前时间】"
--> "更新申请单到数据库"
-->(*)
@enduml
