@startuml
(*)  --> "获得参数1申请单号和参数2处理意见"
-->"申请单持久化调用findById获得申请单"
note right: applicationRepository的方法
--> "设置申请单状态为 拒绝"
--> "设置申请单处理人为【当前登录用户】"
--> "设置处理意见为参数2"
--> "设置处理时间为【当前时间】"
--> "更新申请单到数据库"
-->(*)
@enduml